@startuml class
object User {
  id: integer PK
  authId: varchar
  username: varchar(50)
  mail: varchar
}

object Relationship {
  id: integer PK
  userId: integer FK
  name: varchar
}

object Story {
  id: integer PK
  userId: integer FK
  text: varchar
}

object Relationship_Group {
  id: integer PK
  userId: integer FK
  label: varchar(50)
}

Story "0..*" -- "1..*" Relationship
User "1" -- "0..*" Relationship
User "1" -- "0..*" Story
User "1" -- "0..*" Relationship_Group
Relationship_Group "0..*" -- "1..*" Relationship

@enduml